"""Update user model for mobile app compatibility

Revision ID: 92909e7f8327
Revises: a6e612a7d1e1
Create Date: 2025-07-09 16:29:34.476498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92909e7f8327'
down_revision = 'a6e612a7d1e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns safely - if they don't already exist
    try:
        op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    except Exception:
        pass
    
    try:
        op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    except Exception:
        pass
    
    try:
        op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    except Exception:
        pass
    
    try:
        op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    except Exception:
        pass
    
    try:
        op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    except Exception:
        pass
    
    try:
        op.add_column('users', sa.Column('additional_data', sa.JSON(), nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('users', 'additional_data')
    except Exception:
        pass
    
    try:
        op.drop_column('users', 'profile_picture')
    except Exception:
        pass
    
    try:
        op.drop_column('users', 'address')
    except Exception:
        pass
    
    try:
        op.drop_column('users', 'phone')
    except Exception:
        pass
    
    try:
        op.drop_column('users', 'employee_id')
    except Exception:
        pass
    
    try:
        op.drop_column('users', 'position')
    except Exception:
        pass
    # ### end Alembic commands ### 