"""Update user model for mobile app compatibility

Revision ID: a6e612a7d1e1
Revises: 
Create Date: 2025-07-09 16:26:06.209530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6e612a7d1e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('users', 'additional_data')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'position')
    op.drop_column('users', 'name')
    # ### end Alembic commands ### 